apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: runtime-nodejs-example-module
  namespace: default
spec:
  build:
    source:
      git:
        url: https://github.com/solsson/docker-riff.git
        revision: master
    template:
      name: runtime-nodejs
      # probably to be replaced with ClusterBuildTemplate: namespace: build-templates
      arguments:
      - name: _IMAGE
        value: registry.munu.io/solsson/runtime-nodejs-example-module
      - name: _ENTRY_POINT
        value: todo-select-language-dependent-entrypoint
      - name: DIRECTORY
        value: ./test-nodejs-packagelock

  revisionTemplate:
    metadata:
      labels:
        knative.dev/type: "function"
    spec:
      container:
        # image either provided as pre-built container, or built by Knative Serving from
        # source. When built by knative, set to the same as build template, e.g.
        # build.template.arguments[_IMAGE], as the "promise" of a future build.
        image: registry.munu.io/solsson/runtime-nodejs-example-module
        command: ['run']
        args: []
        env:
        - name: FOO
          value: bar
        - name: HELLO
          value: world
