apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: runtime-nodejs-example-module
  namespace: default
spec:
  build:
    source:
      git:
        url: https://github.com/jrandom/myrepo
        commit: master
    template:
      name: runtime-nodejs
      namespace: build-templates
      arguments:
      - name: _IMAGE
        value: gcr.io/...  # destination for image
      - name: _ENTRY_POINT
        value: index  # if function, language dependent entrypoint

  revisionTemplate:
    metadata:
      labels:
        knative.dev/type: "function"
    spec:
      container:
        # image either provided as pre-built container, or built by Knative Serving from
        # source. When built by knative, set to the same as build template, e.g.
        # build.template.arguments[_IMAGE], as the "promise" of a future build.
        image: gcr.io/...
        command: ['run']
        args: []
        env:
        # list of environment vars
        - name: FOO
          value: bar
        - name: HELLO
          value: world
        - ...
        livenessProbe: ...  # Optional
        readinessProbe: ...  # Optional
      containerConcurrency: ...
      timeoutSeconds: ...
      serviceAccountName: ...  # Name of the service account the code should run as.
